# Generated by Django 4.0.6 on 2023-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_reserva_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_pessoas',
            field=models.IntegerField(default=1),
        ),
    ]
